### ISSUE TITLE
What's new about this model?

### ISSUE THREAD

**Issue by vztu** [tmp-iclr/convmixer#3]
Why “patches” are all you need? 
Patch embedding is Conv7x7 stem,
The body is simply repeated Conv9x9 + Conv1x1,
(Not challenging your work, it's indeed very interesting), but just kindly wondering what's new about this model?

**Comment by tmp-iclr** [comment]
Some models do indeed use a stem with k = 7 convolutions, but this is often with stride = 2. The patch embedding stem sets kernel size equal to patch size, which reduces size more than stride = 2. That is, all the dimension reduction happens immediately at the stem, in contrast to most CNNs where it happens gradually throughout the model (i.e., "pyramid shaped").

It's also unusual that we use k = 9 convolutions at all, as typically stacked small-kernel convolutions are favored.

Overall, the model is exceedingly simple yet still performs very well in terms of accuracy.

**Comment by rentainhe** [comment]
Thanks for your reply : ), I hope this paper can be accepted in ICLR 2022~
