### ISSUE TITLE
Experiments with full convolutional layers instead of patch embedding？

### ISSUE THREAD

**Issue by forjiuzhou** [tmp-iclr/convmixer#4]
Have the author tried to replace the patch embedding with the just convolution？That is, using 1 stride instead of p？

With this setting, this is a standard convolution network like MobileNet. I wonder what would be the performance？Is the performance gain of Convmix due to the patch embedding or the depthwise conv layers？

Very interested in this work, thanks.

**Comment by tmp-iclr** [comment]
I'm going to close this issue, but feel free to reopen it or open a new issue if you have more questions.
